### ISSUE TITLE
0.0.1

### ISSUE THREAD

**Issue by rmehta** [erpnext/hub#10]
- [ ] hub.erpnext.org
  - [ ] home page
  - [ ] about
  - [ ] terms
- [ ] hub icon
- [ ] hub client (inside desk)
  - [ ] sign up (description etc) (hub settings)
    - [ ] edit listing
  - [ ] company listing
  - [ ] product listing
  - [ ] company page
    - [ ] description
    - [ ] address and contact
    - [ ] image
  - [ ] product page
    - [ ] description
    - [ ] image
    - [ ] request a quote
- [ ] sync
 - [ ] Item
   - [ ] hub_url (https://hub.erpnext.org/company/item)

**Comment by achillesrasquinha** [comment]
Closing, Moved to Hub Roadmap
